### ISSUE TITLE
Added / forgotten resource

### ISSUE THREAD

**Issue by MaamuT** [aquasarus/Starfield-Interactive-Smart-Slate#14]
In the list of selectable resources you should add "various".

On the net, for the Terramorph, it is indicated that it can loot "various" resources.

**Comment by aquasarus** [comment]
Interesting! Could it be a French translation discrepancy? In my game it says "None", so I've added that as an option specifically for Terrormorphs.

**Comment by MaamuT** [comment]
In french, various = "variables"

In this sheet : https://docs.google.com/spreadsheets/d/1rpOtCg_4EP86LOkCNTLFPapUrKI1afgJWKcfJXarlBI/edit#gid=912185039

On the page for Toliman, yo see terramorph with Various resources.

**Comment by aquasarus** [comment]
Ah, my bad. It seems like the game doesn't say anything at all. I must have decided to use "None" because the Resource property is meant to indicate a guaranteed drop, for which there is none in a Terrormorph. I suppose the argument could be made for "Various" as well. In either case, the functionality is already there in the app, so you can catalog a Terrormorph with no problems. Just choose "None" in the resource dropdown and it will count as surveyed.

![Screenshot](https://i.imgur.com/1FOXmZ9.jpg)

**Comment by MaamuT** [comment]
That's what I did, I set None.

Are you planning to put Various in an update?

**Comment by aquasarus** [comment]
My intention with the app is to stay as true to the in-game information as possible. My interpretation here is that Terrormorphs have no guaranteed resource drops. Therefore, "None" makes more sense than "Various". It's just a word choice really, just like how the person who made your spreadsheet chose "Various" to indicate that Terrormorphs can drop a lot of different things (as do all other Faunas). The underlying implementation remains the same either way. So, no, there are no plans to change the wording at the moment.
