### ISSUE TITLE
Serpentis IV 13 animals, not 12

### ISSUE THREAD

**Issue by MaamuT** [aquasarus/Starfield-Interactive-Smart-Slate#23]
Impossible to add an animal species, it's stuck at 12 even though there are 13.

**Comment by aquasarus** [comment]
Fixed in [v1.3.2](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/releases/tag/v1.3.2)!
Also FYI there is a setting that lets you unlock the total fauna/flora counts. So if you find another issue like this, you can unlock it so that it won't prevent you from adding lifeforms. 

![image](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/assets/1495089/73c527a4-f301-4c05-b6f2-8754a2dc4035)
